document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>项目-海澜之家官方商城</title>");
document.writeln("    <link rel=\'shortcut icon\' href=\'images/favcion.ico\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'./css/public-head.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <!-- 公共顶部 -->");
document.writeln("    <div id=\'top\'>");
document.writeln("        <div class=\'top-con\'>");
document.writeln("            <div class=\'fl top_l\'>");
document.writeln("                <ul>");
document.writeln("                    <li>你好，欢迎来到海澜之家!</li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>请登录</a>");
document.writeln("                        <span class=\'top_ml\'></span>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        合作账号登录");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>");
document.writeln("                            <img src=\'http://www.hlamall.cn:80/img/pc-site/logo10.jpg\' alt=\'\'>");
document.writeln("                        </a>");
document.writeln("                        <a href=\'\'>");
document.writeln("                            <img src=\'http://www.hlamall.cn:80/img/pc-site/qqimg.jpg\' alt=\'\'>");
document.writeln("                        </a>");
document.writeln("                        <a href=\'\'>");
document.writeln("                            <img src=\'http://www.hlamall.cn:80/img/pc-site/alipay.png\' alt=\'\'>");
document.writeln("                        </a>");
document.writeln("                        <span class=\'top_ml\'></span>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>免费注册</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'fr top_r\'>");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>我的海澜之家</a>");
document.writeln("                        <span class=\'top_ml\'></span>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>在线客服</a>");
document.writeln("                        <span class=\'top_ml\'></span>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>我的购物袋有0件商品</a>");
document.writeln("                        <span class=\'top_ml\'></span>");
document.writeln("                    </li>");
document.writeln("                    <li><a href=\'#\'>帮助</a></li>");
document.writeln("                    <li><a href=\'#\'>");
document.writeln("                        <span>");
document.writeln("                            <i></i>");
document.writeln("                            <span style='display: inline;'>加关注</span>");
document.writeln("                        </span>");
document.writeln("                    </a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("        <!-- 搜索 -->");
document.writeln("    <div id=\'logosearch\'>");
document.writeln("        <div class=\'logosearch-con\'>");
document.writeln("            <div class=\'NearbyStores\'>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>附近门店</a>");
document.writeln("                </li>");
document.writeln("            </div>");
document.writeln("            <div class=\'logoSc-logo\'>");
document.writeln("                <img src=\'./images/head_logo.jpg\' alt=\'\'>");
document.writeln("            </div>");
document.writeln("            <div class=\'logoSc-search\'>");
document.writeln("                <input type=\'text\' value=\'大闹天宫\'>");
document.writeln("                <input type=\'submit\' value=\'\'>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("        <!-- 导航 -->");
document.writeln("    <div id=\'public-nav\'>");
document.writeln("        <div class=\'public-nav-con\'>");
document.writeln("            <ul>");
document.writeln("                <li>");
document.writeln("                    <a href=\'./home.html\'>首页</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>大闹天宫</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>商场同款</a>");
document.writeln("                </li>");
document.writeln("                <li id=\'new-product\'>");
document.writeln("                    <a href=\'#\'>夏季新品</a>");
document.writeln("                </li>");
document.writeln("                <li id=\'hot-spring-sale\'> ");
document.writeln("                    <a href=\'#\'>春季热卖</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>衬衫</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>卫衣</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>针织衫</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>T恤</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>POLO</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>夹克</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>林更新同款</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>休闲裤</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>牛仔裤</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>中裤</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'#\'>西服</a>");
document.writeln("                </li>");
document.writeln("                <li id=\'accessory\'>");
document.writeln("                    <a href=\'#\'>配饰</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div id=\'nav-show-box\'>");
document.writeln("    <div class=\'new-product-box\'>");
document.writeln("        <ul>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>短袖T恤</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>短袖POLO</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>短袖衬衫</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>休闲上衣</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>皮肤衣夹克</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>牛仔九分裤</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>休闲九分裤</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>牛仔中裤</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>休闲中裤</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("        <img src=\'https://gdp.alicdn.com/imgextra/i3/693060164/O1CN01JoHhQn1D59SW31giz_!!693060164.jpg\' alt=\'\'>");
document.writeln("    </div>");
document.writeln("    <div class=\'hot-spring-sale-box\'>");
document.writeln("        <ul>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>卫衣</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>长袖衬衫</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>针织衫</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>夹克</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>牛仔外套</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>风衣</a>");
document.writeln("            </li>");
document.writeln("            ");
document.writeln("        </ul>");
document.writeln("        <img src=\'https://gdp.alicdn.com/imgextra/i3/693060164/O1CN01cDOl7i1D59R8nmtbY_!!693060164.jpg\' alt=\'\'>");
document.writeln("    </div>");
document.writeln("    <div class=\'accessory-box\'>");
document.writeln("        <ul>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>皮带</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>领带</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>领结</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>太阳镜</a>");
document.writeln("                <a class=\'pb-bd\' href=\'\'></a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'>男鞋</a>");
document.writeln("");
document.writeln("            </li>");
document.writeln("            ");
document.writeln("            ");
document.writeln("        </ul>");
document.writeln("        <img src=\'https://gdp.alicdn.com/imgextra/i1/693060164/O1CN011D59PleXgJP4tRk_!!693060164.jpg\' alt=\'\'>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("<script src=./js/public-head.js></script>");
document.writeln("</html>");